config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}
  # resources :categories
  # resources :deals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :splash, only: %i[index]
  get '/users/reset_password', to: 'users#reset_password_view'
  resources :users do
    patch :reset_password, on: :member
  end
  root "splash#index"
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :deals, only: [:index, :new, :create ]
  end

end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  belongs_to :category, class_name: 'Category', foreign_key: :category_id

  validates :title, presence: true, length: { minimum: 1 }
  validates :amount, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]

  # GET /deals or /deals.json
  def index
    @deals = Deal.where(category_id: params[:category_id]).order(created_at: :desc)
    @category = Category.find(params[:category_id])
  end

  # GET /deals/1 or /deals/1.json
  def show; end

  # GET /deals/new
  def new
    @deal = Deal.new
    @category = Category.find(params[:category_id])
    p @category
  end

  # GET /deals/1/edit
  def edit; end

  # POST /deals or /deals.json
  def create
    @user = current_user
    @category = Category.find(params[:category_id])
    @deal = Deal.create(user: current_user, category_id: @category.id, title: deal_params['title'],
                        amount: deal_params['amount'])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to category_deals_path(@category) }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deal_url(@deal), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to category_deals_path, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:title, :amount, :icon, :user_id, :category_id)
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal.html.erb
<div id="<%= dom_id deal %>" class="category-item">
  <div class="category-det">
    <h4 class="cat-det">Deal N* <%= deal.id.to_s.rjust(5, "0") %></h4>
    <h4 class="cat-det"> Title : <%= deal.title %></h4>
  </div>
  <div class="category-item-right">
    <h4 class="cat-det">$ <%= deal.amount %></h4>
  </div>
</div>

app/views/deals/_form.html.erb
<%= form_with(model: deal) do |form| %>
  <% if deal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/deals/index.html.erb
<div class="category-ctn">
  <div class="category-nav">
    <%= link_to categories_path do %>
      <h2><</h2>
    <% end %>
    <div class="nav-title-ctn">
      <h3 class="nav-title">Deals</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>
  <div class="price-band">
    <h5>Total amount : </h5>
    <h5>$ <%= @deals.map { |deal| deal.amount }.sum %></h5>
  </div>

  <div id="deals">
    <% @deals.each do |deal| %>
      <%= render deal %>
      <%#= button_to "Remove", category_deal_path(@category, deal), method: :delete %>
    <% end %>
  </div>

  <div class="bottom-button">
    <%= link_to "New deal", new_category_deal_path, class: 'but-default bottom-btn' %>
  </div>
</div>

app/views/deals/new.html.erb
<div class="cate-create-ctn">
  <div class="category-nav">
    <%= link_to category_deals_path do %>
      <h2></h2>
    <% end %>
    <div class="nav-title-ctn">
      <h3 class="nav-title">New Deal</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>

  <%= form_with model: @deal, url: category_deals_path, method: :post, class: 'form' do |form| %>
    <% if @deal.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

        <ul>
          <% @deal.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", required: true %>
    </div>

    <div class="field">
      <%= form.number_field :amount, autofocus: true, placeholder: "Amount", required: true %>
    </div>

    <div class="button-link">
      <%= form.submit "Valider", class: 'but-default' %>
    </div>
  <% end %>
</div>

app/views/deals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deal %>

<div>
  <%= link_to "Edit this deal", edit_deal_path(@deal) %> |
  <%= link_to "Back to deals", deals_path %>

  <%= button_to "Destroy this deal", @deal, method: :delete %>
</div>