config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "sessions"}
  # resources :categories
  # resources :deals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :splash, only: %i[index]
  get '/users/reset_password', to: 'users#reset_password_view'
  resources :users do
    patch :reset_password, on: :member
  end
  root "splash#index"
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :deals, only: [:index, :new, :create ]
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :deals
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  validates :title, presence: true, length: { minimum: 1 }
  validates :icon, presence: true
end

app/controllers/categories_controller.rb
require 'base64'

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    redirect_to new_user_session_path if user_signed_in? == false
    @categories = Category.where(user_id: current_user.id)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @deals = Deal.where(category_id: params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    file_content = File.read(category_params['icon'].tempfile, &:read)
    encoded_string = Base64.strict_encode64(file_content)
    @category = Category.create(user: current_user, title: category_params['title'],
                                description: category_params['description'], icon: encoded_string)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to categories_path, notice: 'Picture was successfully created.'
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:icon, :title, :description)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category-item-left">
  <div class="cat-img-ctn">
      <%= image_tag "data:image/png;base64,#{category.icon}", :class => "category-img" %>
  </div>
  <div class="category-det">
    <h5 class="cat-det"><%= category.title %></h5>
    <h5 class="cat-det date">$ <%= category.deals.map{|deal| deal.amount }.sum %></h5>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title, autofocus: true, placeholder: 'Title', required: true%>
  </div>
  <div class="field">
  <%= form.text_field :description, autofocus: true, placeholder: 'Description', required: true%>
</div>
  <div class="field">
    <%= form.file_field :icon, autofocus: true, placeholder: 'Icon', required: true %>
  </div>

  <div class="button-link">
    <%= form.submit "Valider", class: 'but-default' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="category-ctn">
  <div class="category-nav">
  <div> </div>
    <div class="nav-title-ctn">

      <h3 class="nav-title">Categories</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>
  <div id="categories" class="category-list-ctn">
    <% if @categories.count != 0 %>
    <% @categories.each do |category| %>
      <%= link_to category_deals_path(category.id) do %>
      <div class="category-item">
        <%= render category %>
        <div class="category-item-right">
          <%= button_to 'Details', category_path(category), method: :delete, class: "btn-rmv"%>
        </div>
      </div>
      <% end %>
    <% end %>
      <%end %>
  </div>

  <div class="bottom-button">
    <%= link_to "New category", new_category_path, class: 'but-default bottom-btn'%>
  </div>
</div>

app/views/categories/new.html.erb
<div class="cate-create-ctn">
  <div class="category-nav">
    <%= link_to categories_path do %>
      <h2><</h2>
    <% end %>
    <div class="nav-title-ctn">
      <h3 class="nav-title">New category</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>
  <%= render "form", category: @category %>

</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <div>
    <h5>Total amount : </h5>
    <h5><%= @deals.inject(0, :+) %></h5>
  </div>
  <% @deals.each do |deal| %>
    <p><%= deal.name %></p>
    <p><%= deal.amount %></p>
    <p><%= deal.id %></p>
  <% end %>
</div>

<div>

  <div>
    <%= link_to "Add new transaction", new_category_deal_path(@category) %>
  </div>
  <%= link_to "Back to categories", :back %>

  <%#= button_to "Destroy this category", @category, method: :delete %>
</div>